name = "psycopoint-backend"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat_v2" ]
# route = "api.psycopoint.com"

[vars]
PROJECT_NAME = "psycopoint"
FRONTEND_URL = "https://app.psycopoint.com"
BACKEND_URL = "https://api.psycopoint.com/v1"
DOMAIN = "psycopoint.com"
# FRONTEND_URL = "http://localhost:3000"
# BACKEND_URL = "http://127.0.0.1:3001/v1"
# DOMAIN = "127.0.0.1"
SESSION_DURATION = 7
DEFAULT_UPLOAD_SIZE = 2
LOGO_URL= "https://media.psycopoint.com/logo.png"

[ai]
binding = "AI"

[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

