export type Env = {
  DATABASE_URL: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  PROJECT_NAME: string;
  SESSION_SECRET: string;
  FRONTEND_URL: string;
  RESEND_API_KEY: string;
  COOKIE_DOMAIN: string;
  LEMONSQUEEZY_STORE_ID: string;
  LEMONSQUEEZY_MONTHLY_VARIANT_ID: string;
  LEMONSQUEEZY_WEBHOOK_SECRET: string;
  LEMONSQUEEZY_API_KEY: string;
};
